---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: slack-pipeline
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: release
spec:
  description: "Pushes an artifact to quay.io"
  params:
    - name: snapshotPath
      type: string
    - name: dataPath
      type: string
    - name: resultsDirPath
      type: string
  workspaces:
    - name: release-workspace
  tasks:
    - name: push-to-quay
      taskRef:
        resolver: "git"
        params:
          - name: url
            value: https://github.com/Paul123111/community-catalog.git
          - name: revision
            value: development
          - name: pathInRepo
            value: tasks/push-to-quay/push-to-quay-task.yaml
      params:
        - name: snapshotPath
          value: $(params.snapshotPath)
        - name: dataPath
          value: $(params.dataPath)
        - name: resultsDirPath
          value: $(params.resultsDirPath)
      workspaces:
        - name: data
          workspace: release-workspace