---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: notify-slack-on-failure-sample
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: release
spec:
  description: Sample pipeline that runs the "notify-slack-on-failure" task
  params:
    - name: secretName
      type: string
    - name: secretKeyName
      type: string
    - name: release
      type: string
  workspaces:
    - name: release-workspace
  tasks:
    - name: notify-slack-on-failure
      taskRef:
        resolver: "git"
        params:
          - name: url
            value: https://github.com/Paul123111/community-catalog.git
          - name: revision
            value: development
          - name: pathInRepo
            value: tasks/notify-slack-on-failure/notify-slack-on-failure.yaml
      params:
        - name: secretName
          value: $(params.secretName)
        - name: secretKeyName
          value: $(params.secretKeyName)
        - name: RELEASE
          value: $(params.release)
      workspaces:
        - name: data
          workspace: release-workspace